### list
http://localhost:9527/api/book
### get
http://localhost:9527/api/book/2854865600512
### create
POST http://localhost:9527/api/book
Content-Type: application/json

{"title":"时间简史"}

### update
PUT http://localhost:9527/api/book/2854865600512
Content-Type: application/json

{"title":"时间简史2"}

### delete
DELETE  http://localhost:9527/api/book/2854967312384
### 错误的增加
POST http://localhost:9527/api/book
Content-Type: application/json

{"title":""}

