// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: cmd/demo/pb/msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_ping  Type = 0
	Type_icons Type = 1
	Type_info  Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "ping",
		1: "icons",
		2: "info",
	}
	Type_value = map[string]int32{
		"ping":  0,
		"icons": 1,
		"info":  2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_demo_pb_msg_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_cmd_demo_pb_msg_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_cmd_demo_pb_msg_proto_rawDescGZIP(), []int{0}
}

// Msg 消息.
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   Type              `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Type" json:"type,omitempty"`
	Data   string            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Number int64             `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Count  int64             `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Text   string            `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Offset int64             `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Icons  []string          `protobuf:"bytes,7,rep,name=icons,proto3" json:"icons,omitempty"`
	Info   map[string]string `protobuf:"bytes,8,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_demo_pb_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_demo_pb_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_cmd_demo_pb_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_ping
}

func (x *Msg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Msg) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Msg) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Msg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Msg) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Msg) GetIcons() []string {
	if x != nil {
		return x.Icons
	}
	return nil
}

func (x *Msg) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_cmd_demo_pb_msg_proto protoreflect.FileDescriptor

var file_cmd_demo_pb_msg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6d, 0x64, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x73,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x87, 0x02, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x63, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x49, 0x6e, 0x66,
	0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x37, 0x0a, 0x09,
	0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x25, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x02, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_demo_pb_msg_proto_rawDescOnce sync.Once
	file_cmd_demo_pb_msg_proto_rawDescData = file_cmd_demo_pb_msg_proto_rawDesc
)

func file_cmd_demo_pb_msg_proto_rawDescGZIP() []byte {
	file_cmd_demo_pb_msg_proto_rawDescOnce.Do(func() {
		file_cmd_demo_pb_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_demo_pb_msg_proto_rawDescData)
	})
	return file_cmd_demo_pb_msg_proto_rawDescData
}

var file_cmd_demo_pb_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_demo_pb_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_demo_pb_msg_proto_goTypes = []interface{}{
	(Type)(0),   // 0: pb.Type
	(*Msg)(nil), // 1: pb.Msg
	nil,         // 2: pb.Msg.InfoEntry
}
var file_cmd_demo_pb_msg_proto_depIdxs = []int32{
	0, // 0: pb.Msg.type:type_name -> pb.Type
	2, // 1: pb.Msg.info:type_name -> pb.Msg.InfoEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_demo_pb_msg_proto_init() }
func file_cmd_demo_pb_msg_proto_init() {
	if File_cmd_demo_pb_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_demo_pb_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_demo_pb_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_demo_pb_msg_proto_goTypes,
		DependencyIndexes: file_cmd_demo_pb_msg_proto_depIdxs,
		EnumInfos:         file_cmd_demo_pb_msg_proto_enumTypes,
		MessageInfos:      file_cmd_demo_pb_msg_proto_msgTypes,
	}.Build()
	File_cmd_demo_pb_msg_proto = out.File
	file_cmd_demo_pb_msg_proto_rawDesc = nil
	file_cmd_demo_pb_msg_proto_goTypes = nil
	file_cmd_demo_pb_msg_proto_depIdxs = nil
}
